### ISSUE TITLE
managed-html5-runtime-fiori-mta doesn't work

### ISSUE THREAD

**Issue by superwangnan** [SAP-samples/multi-cloud-html5-apps-samples#30]
Hi team
I am trying to deploy managed-html5-runtime-fiori-mta to BTP trial (US10). I got the error as screenshot in attachment.
Please help 

Thanks in advanced.
![error](https://user-images.githubusercontent.com/20192234/143460054-664f5798-79a9-4199-a1f4-2db63515af13.jpg)

**Comment by IObert** [comment]
I don't see a relevant error in this screenshot (there are a few only errors about requests that couldn't be loaded because this Northwind OData service is missing some annotations).  These missing annotations are also the reason why there is no Object page to create new entities. 

Does this explain what you see or were you referring to another problem that I can't see?

**Comment by nicoschoenteich** [comment]
Is this still relevant? The example works fine for me. I couldn't reproduce the issue, although I do get the same error messages.
